site_name: Yukini-Sakuhana
theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
        primary: black
        accent: cyan
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
# nav:
#   - 碎碎念:
#     - 岁岁念: suisuininan/begin.md
