site_name: Yukini-Sakuhana
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon: 
    repo: fontawesome/brands/github #右上角图标
nav:
    - 见闻录: 
      - 破防的暑期总结(与碎碎念中一致): MyBlogs/Daily_News/End_Of_July.md
      - bash学习: MyBlogs/Daily_News/Bash.md
    - 碎碎念:
      - 岁岁念: suisuinian/begin.md
      - 暑期小结: suisuinian/End_Of_July.md
    - 阅读笔记:
      - CSAPP918: MyBlogs/Suread/CSAPP1.md
